const CACHE_NAME = 'chess-v1';
const PRE_CACHE = [
  '/',
  '/index.html',
  '/src/main.js',
  '/src/styles/main.css',
  '/public/stockfish.js',
  '/public/stockfish.wasm',

  // PWA Icons
  '/public/icons/icon-192.png',
  '/public/icons/icon-512.png',

  // Piece Style CSS
  '/public/piece-css/alpha.css',
  '/public/piece-css/anarcandy.css',
  '/public/piece-css/caliente.css',
  '/public/piece-css/california.css',
  '/public/piece-css/cardinal.css',
  '/public/piece-css/cburnett.css',
  '/public/piece-css/celtic.css',
  '/public/piece-css/chess7.css',
  '/public/piece-css/chessnut.css',
  '/public/piece-css/companion.css',
  '/public/piece-css/cooke.css',
  '/public/piece-css/disguised.css',
  '/public/piece-css/dubrovny.css',
  '/public/piece-css/fantasy.css',
  '/public/piece-css/firi.css',
  '/public/piece-css/fresca.css',
  '/public/piece-css/gioco.css',
  '/public/piece-css/governor.css',
  '/public/piece-css/horsey.css',
  '/public/piece-css/icpieces.css',
  '/public/piece-css/kiwen-suwi.css',
  '/public/piece-css/kosal.css',
  '/public/piece-css/leipzig.css',
  '/public/piece-css/letter.css',
  '/public/piece-css/maestro.css',
  '/public/piece-css/merida.css',
  '/public/piece-css/monarchy.css',
  '/public/piece-css/mpchess.css',
  '/public/piece-css/pirouetti.css',
  '/public/piece-css/pixel.css',
  '/public/piece-css/reillycraig.css',
  '/public/piece-css/rhosgfx.css',
  '/public/piece-css/riohacha.css',
  '/public/piece-css/shapes.css',
  '/public/piece-css/spatial.css',
  '/public/piece-css/staunty.css',
  '/public/piece-css/tatiana.css',
  '/public/piece-css/xkcd.css',

  // SVG Pieces
  // Alpha set
  '/public/pieces/alpha/bB.svg',
  '/public/pieces/alpha/bK.svg',
  '/public/pieces/alpha/bN.svg',
  '/public/pieces/alpha/bP.svg',
  '/public/pieces/alpha/bQ.svg',
  '/public/pieces/alpha/bR.svg',
  '/public/pieces/alpha/wB.svg',
  '/public/pieces/alpha/wK.svg',
  '/public/pieces/alpha/wN.svg',
  '/public/pieces/alpha/wP.svg',
  '/public/pieces/alpha/wQ.svg',
  '/public/pieces/alpha/wR.svg',
  // Anarcandy set
  '/public/pieces/anarcandy/bB.svg',
  '/public/pieces/anarcandy/bK.svg',
  '/public/pieces/anarcandy/bN.svg',
  '/public/pieces/anarcandy/bP.svg',
  '/public/pieces/anarcandy/bQ.svg',
  '/public/pieces/anarcandy/bR.svg',
  '/public/pieces/anarcandy/wB.svg',
  '/public/pieces/anarcandy/wK.svg',
  '/public/pieces/anarcandy/wN.svg',
  '/public/pieces/anarcandy/wP.svg',
  '/public/pieces/anarcandy/wQ.svg',
  '/public/pieces/anarcandy/wR.svg',
  // Caliente set
  '/public/pieces/caliente/bB.svg',
  '/public/pieces/caliente/bK.svg',
  '/public/pieces/caliente/bN.svg',
  '/public/pieces/caliente/bP.svg',
  '/public/pieces/caliente/bQ.svg',
  '/public/pieces/caliente/bR.svg',
  '/public/pieces/caliente/wB.svg',
  '/public/pieces/caliente/wK.svg',
  '/public/pieces/caliente/wN.svg',
  '/public/pieces/caliente/wP.svg',
  '/public/pieces/caliente/wQ.svg',
  '/public/pieces/caliente/wR.svg',
  // California set
  '/public/pieces/california/bB.svg',
  '/public/pieces/california/bK.svg',
  '/public/pieces/california/bN.svg',
  '/public/pieces/california/bP.svg',
  '/public/pieces/california/bQ.svg',
  '/public/pieces/california/bR.svg',
  '/public/pieces/california/wB.svg',
  '/public/pieces/california/wK.svg',
  '/public/pieces/california/wN.svg',
  '/public/pieces/california/wP.svg',
  '/public/pieces/california/wQ.svg',
  '/public/pieces/california/wR.svg',
  // Cardinal set
  '/public/pieces/cardinal/bB.svg',
  '/public/pieces/cardinal/bK.svg',
  '/public/pieces/cardinal/bN.svg',
  '/public/pieces/cardinal/bP.svg',
  '/public/pieces/cardinal/bQ.svg',
  '/public/pieces/cardinal/bR.svg',
  '/public/pieces/cardinal/wB.svg',
  '/public/pieces/cardinal/wK.svg',
  '/public/pieces/cardinal/wN.svg',
  '/public/pieces/cardinal/wP.svg',
  '/public/pieces/cardinal/wQ.svg',
  '/public/pieces/cardinal/wR.svg',
  // Cburnett set
  '/public/pieces/cburnett/bB.svg',
  '/public/pieces/cburnett/bK.svg',
  '/public/pieces/cburnett/bN.svg',
  '/public/pieces/cburnett/bP.svg',
  '/public/pieces/cburnett/bQ.svg',
  '/public/pieces/cburnett/bR.svg',
  '/public/pieces/cburnett/wB.svg',
  '/public/pieces/cburnett/wK.svg',
  '/public/pieces/cburnett/wN.svg',
  '/public/pieces/cburnett/wP.svg',
  '/public/pieces/cburnett/wQ.svg',
  '/public/pieces/cburnett/wR.svg',
  // Celtic set
  '/public/pieces/celtic/bB.svg',
  '/public/pieces/celtic/bK.svg',
  '/public/pieces/celtic/bN.svg',
  '/public/pieces/celtic/bP.svg',
  '/public/pieces/celtic/bQ.svg',
  '/public/pieces/celtic/bR.svg',
  '/public/pieces/celtic/wB.svg',
  '/public/pieces/celtic/wK.svg',
  '/public/pieces/celtic/wN.svg',
  '/public/pieces/celtic/wP.svg',
  '/public/pieces/celtic/wQ.svg',
  '/public/pieces/celtic/wR.svg',
  // Chess7 set
  '/public/pieces/chess7/bB.svg',
  '/public/pieces/chess7/bK.svg',
  '/public/pieces/chess7/bN.svg',
  '/public/pieces/chess7/bP.svg',
  '/public/pieces/chess7/bQ.svg',
  '/public/pieces/chess7/bR.svg',
  '/public/pieces/chess7/wB.svg',
  '/public/pieces/chess7/wK.svg',
  '/public/pieces/chess7/wN.svg',
  '/public/pieces/chess7/wP.svg',
  '/public/pieces/chess7/wQ.svg',
  '/public/pieces/chess7/wR.svg',
  // Chessnut set
  '/public/pieces/chessnut/bB.svg',
  '/public/pieces/chessnut/bK.svg',
  '/public/pieces/chessnut/bN.svg',
  '/public/pieces/chessnut/bP.svg',
  '/public/pieces/chessnut/bQ.svg',
  '/public/pieces/chessnut/bR.svg',
  '/public/pieces/chessnut/wB.svg',
  '/public/pieces/chessnut/wK.svg',
  '/public/pieces/chessnut/wN.svg',
  '/public/pieces/chessnut/wP.svg',
  '/public/pieces/chessnut/wQ.svg',
  '/public/pieces/chessnut/wR.svg',
  // Companion set
  '/public/pieces/companion/bB.svg',
  '/public/pieces/companion/bK.svg',
  '/public/pieces/companion/bN.svg',
  '/public/pieces/companion/bP.svg',
  '/public/pieces/companion/bQ.svg',
  '/public/pieces/companion/bR.svg',
  '/public/pieces/companion/wB.svg',
  '/public/pieces/companion/wK.svg',
  '/public/pieces/companion/wN.svg',
  '/public/pieces/companion/wP.svg',
  '/public/pieces/companion/wQ.svg',
  '/public/pieces/companion/wR.svg',
  // Cooke set
  '/public/pieces/cooke/bB.svg',
  '/public/pieces/cooke/bK.svg',
  '/public/pieces/cooke/bN.svg',
  '/public/pieces/cooke/bP.svg',
  '/public/pieces/cooke/bQ.svg',
  '/public/pieces/cooke/bR.svg',
  '/public/pieces/cooke/wB.svg',
  '/public/pieces/cooke/wK.svg',
  '/public/pieces/cooke/wN.svg',
  '/public/pieces/cooke/wP.svg',
  '/public/pieces/cooke/wQ.svg',
  '/public/pieces/cooke/wR.svg',
  // Disguised set
  '/public/pieces/disguised/b.svg',
  '/public/pieces/disguised/bB.svg',
  '/public/pieces/disguised/bK.svg',
  '/public/pieces/disguised/bN.svg',
  '/public/pieces/disguised/bP.svg',
  '/public/pieces/disguised/bQ.svg',
  '/public/pieces/disguised/bR.svg',
  '/public/pieces/disguised/w.svg',
  '/public/pieces/disguised/wB.svg',
  '/public/pieces/disguised/wK.svg',
  '/public/pieces/disguised/wN.svg',
  '/public/pieces/disguised/wP.svg',
  '/public/pieces/disguised/wQ.svg',
  '/public/pieces/disguised/wR.svg',
  // Dubrovny set
  '/public/pieces/dubrovny/bB.svg',
  '/public/pieces/dubrovny/bK.svg',
  '/public/pieces/dubrovny/bN.svg',
  '/public/pieces/dubrovny/bP.svg',
  '/public/pieces/dubrovny/bQ.svg',
  '/public/pieces/dubrovny/bR.svg',
  '/public/pieces/dubrovny/wB.svg',
  '/public/pieces/dubrovny/wK.svg',
  '/public/pieces/dubrovny/wN.svg',
  '/public/pieces/dubrovny/wP.svg',
  '/public/pieces/dubrovny/wQ.svg',
  '/public/pieces/dubrovny/wR.svg',
  // Fantasy set
  '/public/pieces/fantasy/bB.svg',
  '/public/pieces/fantasy/bK.svg',
  '/public/pieces/fantasy/bN.svg',
  '/public/pieces/fantasy/bP.svg',
  '/public/pieces/fantasy/bQ.svg',
  '/public/pieces/fantasy/bR.svg',
  '/public/pieces/fantasy/wB.svg',
  '/public/pieces/fantasy/wK.svg',
  '/public/pieces/fantasy/wN.svg',
  '/public/pieces/fantasy/wP.svg',
  '/public/pieces/fantasy/wQ.svg',
  '/public/pieces/fantasy/wR.svg',
  // Firi set
  '/public/pieces/firi/bB.svg',
  '/public/pieces/firi/bK.svg',
  '/public/pieces/firi/bN.svg',
  '/public/pieces/firi/bP.svg',
  '/public/pieces/firi/bQ.svg',
  '/public/pieces/firi/bR.svg',
  '/public/pieces/firi/wB.svg',
  '/public/pieces/firi/wK.svg',
  '/public/pieces/firi/wN.svg',
  '/public/pieces/firi/wP.svg',
  '/public/pieces/firi/wQ.svg',
  '/public/pieces/firi/wR.svg',
  // Fresca set
  '/public/pieces/fresca/bB.svg',
  '/public/pieces/fresca/bK.svg',
  '/public/pieces/fresca/bN.svg',
  '/public/pieces/fresca/bP.svg',
  '/public/pieces/fresca/bQ.svg',
  '/public/pieces/fresca/bR.svg',
  '/public/pieces/fresca/wB.svg',
  '/public/pieces/fresca/wK.svg',
  '/public/pieces/fresca/wN.svg',
  '/public/pieces/fresca/wP.svg',
  '/public/pieces/fresca/wQ.svg',
  '/public/pieces/fresca/wR.svg',
  // Gioco set
  '/public/pieces/gioco/bB.svg',
  '/public/pieces/gioco/bK.svg',
  '/public/pieces/gioco/bN.svg',
  '/public/pieces/gioco/bP.svg',
  '/public/pieces/gioco/bQ.svg',
  '/public/pieces/gioco/bR.svg',
  '/public/pieces/gioco/wB.svg',
  '/public/pieces/gioco/wK.svg',
  '/public/pieces/gioco/wN.svg',
  '/public/pieces/gioco/wP.svg',
  '/public/pieces/gioco/wQ.svg',
  '/public/pieces/gioco/wR.svg',
  // Governor set
  '/public/pieces/governor/bB.svg',
  '/public/pieces/governor/bK.svg',
  '/public/pieces/governor/bN.svg',
  '/public/pieces/governor/bP.svg',
  '/public/pieces/governor/bQ.svg',
  '/public/pieces/governor/bR.svg',
  '/public/pieces/governor/wB.svg',
  '/public/pieces/governor/wK.svg',
  '/public/pieces/governor/wN.svg',
  '/public/pieces/governor/wP.svg',
  '/public/pieces/governor/wQ.svg',
  '/public/pieces/governor/wR.svg',
  // Horsey set
  '/public/pieces/horsey/bB.svg',
  '/public/pieces/horsey/bK.svg',
  '/public/pieces/horsey/bN.svg',
  '/public/pieces/horsey/bP.svg',
  '/public/pieces/horsey/bQ.svg',
  '/public/pieces/horsey/bR.svg',
  '/public/pieces/horsey/wB.svg',
  '/public/pieces/horsey/wK.svg',
  '/public/pieces/horsey/wN.svg',
  '/public/pieces/horsey/wP.svg',
  '/public/pieces/horsey/wQ.svg',
  '/public/pieces/horsey/wR.svg',
  // Icpieces set
  '/public/pieces/icpieces/bB.svg',
  '/public/pieces/icpieces/bK.svg',
  '/public/pieces/icpieces/bN.svg',
  '/public/pieces/icpieces/bP.svg',
  '/public/pieces/icpieces/bQ.svg',
  '/public/pieces/icpieces/bR.svg',
  '/public/pieces/icpieces/wB.svg',
  '/public/pieces/icpieces/wK.svg',
  '/public/pieces/icpieces/wN.svg',
  '/public/pieces/icpieces/wP.svg',
  '/public/pieces/icpieces/wQ.svg',
  '/public/pieces/icpieces/wR.svg',
  // Kiwen-Suwi set
  '/public/pieces/kiwen-suwi/bB.svg',
  '/public/pieces/kiwen-suwi/bK.svg',
  '/public/pieces/kiwen-suwi/bN.svg',
  '/public/pieces/kiwen-suwi/bP.svg',
  '/public/pieces/kiwen-suwi/bQ.svg',
  '/public/pieces/kiwen-suwi/bR.svg',
  '/public/pieces/kiwen-suwi/wB.svg',
  '/public/pieces/kiwen-suwi/wK.svg',
  '/public/pieces/kiwen-suwi/wN.svg',
  '/public/pieces/kiwen-suwi/wP.svg',
  '/public/pieces/kiwen-suwi/wQ.svg',
  '/public/pieces/kiwen-suwi/wR.svg',
  // Kosal set
  '/public/pieces/kosal/bB.svg',
  '/public/pieces/kosal/bK.svg',
  '/public/pieces/kosal/bN.svg',
  '/public/pieces/kosal/bP.svg',
  '/public/pieces/kosal/bQ.svg',
  '/public/pieces/kosal/bR.svg',
  '/public/pieces/kosal/wB.svg',
  '/public/pieces/kosal/wK.svg',
  '/public/pieces/kosal/wN.svg',
  '/public/pieces/kosal/wP.svg',
  '/public/pieces/kosal/wQ.svg',
  '/public/pieces/kosal/wR.svg',
  // Leipzig set
  '/public/pieces/leipzig/bB.svg',
  '/public/pieces/leipzig/bK.svg',
  '/public/pieces/leipzig/bN.svg',
  '/public/pieces/leipzig/bP.svg',
  '/public/pieces/leipzig/bQ.svg',
  '/public/pieces/leipzig/bR.svg',
  '/public/pieces/leipzig/wB.svg',
  '/public/pieces/leipzig/wK.svg',
  '/public/pieces/leipzig/wN.svg',
  '/public/pieces/leipzig/wP.svg',
  '/public/pieces/leipzig/wQ.svg',
  '/public/pieces/leipzig/wR.svg',
  // Letter set
  '/public/pieces/letter/bB.svg',
  '/public/pieces/letter/bK.svg',
  '/public/pieces/letter/bN.svg',
  '/public/pieces/letter/bP.svg',
  '/public/pieces/letter/bQ.svg',
  '/public/pieces/letter/bR.svg',
  '/public/pieces/letter/wB.svg',
  '/public/pieces/letter/wK.svg',
  '/public/pieces/letter/wN.svg',
  '/public/pieces/letter/wP.svg',
  '/public/pieces/letter/wQ.svg',
  '/public/pieces/letter/wR.svg',
  // Maestro set
  '/public/pieces/maestro/bB.svg',
  '/public/pieces/maestro/bK.svg',
  '/public/pieces/maestro/bN.svg',
  '/public/pieces/maestro/bP.svg',
  '/public/pieces/maestro/bQ.svg',
  '/public/pieces/maestro/bR.svg',
  '/public/pieces/maestro/wB.svg',
  '/public/pieces/maestro/wK.svg',
  '/public/pieces/maestro/wN.svg',
  '/public/pieces/maestro/wP.svg',
  '/public/pieces/maestro/wQ.svg',
  '/public/pieces/maestro/wR.svg',
  // Merida set
  '/public/pieces/merida/bB.svg',
  '/public/pieces/merida/bK.svg',
  '/public/pieces/merida/bN.svg',
  '/public/pieces/merida/bP.svg',
  '/public/pieces/merida/bQ.svg',
  '/public/pieces/merida/bR.svg',
  '/public/pieces/merida/wB.svg',
  '/public/pieces/merida/wK.svg',
  '/public/pieces/merida/wN.svg',
  '/public/pieces/merida/wP.svg',
  '/public/pieces/merida/wQ.svg',
  '/public/pieces/merida/wR.svg',
  // Monarchy set
  '/public/pieces/monarchy/bB.svg',
  '/public/pieces/monarchy/bK.svg',
  '/public/pieces/monarchy/bN.svg',
  '/public/pieces/monarchy/bP.svg',
  '/public/pieces/monarchy/bQ.svg',
  '/public/pieces/monarchy/bR.svg',
  '/public/pieces/monarchy/wB.svg',
  '/public/pieces/monarchy/wK.svg',
  '/public/pieces/monarchy/wN.svg',
  '/public/pieces/monarchy/wP.svg',
  '/public/pieces/monarchy/wQ.svg',
  '/public/pieces/monarchy/wR.svg',
  // Mono set
  '/public/pieces/mono/B.svg',
  '/public/pieces/mono/K.svg',
  '/public/pieces/mono/N.svg',
  '/public/pieces/mono/P.svg',
  '/public/pieces/mono/Q.svg',
  '/public/pieces/mono/R.svg',
  // Mpchess set
  '/public/pieces/mpchess/bB.svg',
  '/public/pieces/mpchess/bK.svg',
  '/public/pieces/mpchess/bN.svg',
  '/public/pieces/mpchess/bP.svg',
  '/public/pieces/mpchess/bQ.svg',
  '/public/pieces/mpchess/bR.svg',
  '/public/pieces/mpchess/wB.svg',
  '/public/pieces/mpchess/wK.svg',
  '/public/pieces/mpchess/wN.svg',
  '/public/pieces/mpchess/wP.svg',
  '/public/pieces/mpchess/wQ.svg',
  '/public/pieces/mpchess/wR.svg',
  // Pirouetti set
  '/public/pieces/pirouetti/bB.svg',
  '/public/pieces/pirouetti/bK.svg',
  '/public/pieces/pirouetti/bN.svg',
  '/public/pieces/pirouetti/bP.svg',
  '/public/pieces/pirouetti/bQ.svg',
  '/public/pieces/pirouetti/bR.svg',
  '/public/pieces/pirouetti/wB.svg',
  '/public/pieces/pirouetti/wK.svg',
  '/public/pieces/pirouetti/wN.svg',
  '/public/pieces/pirouetti/wP.svg',
  '/public/pieces/pirouetti/wQ.svg',
  '/public/pieces/pirouetti/wR.svg',
  // Pixel set
  '/public/pieces/pixel/bB.svg',
  '/public/pieces/pixel/bK.svg',
  '/public/pieces/pixel/bN.svg',
  '/public/pieces/pixel/bP.svg',
  '/public/pieces/pixel/bQ.svg',
  '/public/pieces/pixel/bR.svg',
  '/public/pieces/pixel/wB.svg',
  '/public/pieces/pixel/wK.svg',
  '/public/pieces/pixel/wN.svg',
  '/public/pieces/pixel/wP.svg',
  '/public/pieces/pixel/wQ.svg',
  '/public/pieces/pixel/wR.svg',
  // Reillycraig set
  '/public/pieces/reillycraig/bB.svg',
  '/public/pieces/reillycraig/bK.svg',
  '/public/pieces/reillycraig/bN.svg',
  '/public/pieces/reillycraig/bP.svg',
  '/public/pieces/reillycraig/bQ.svg',
  '/public/pieces/reillycraig/bR.svg',
  '/public/pieces/reillycraig/wB.svg',
  '/public/pieces/reillycraig/wK.svg',
  '/public/pieces/reillycraig/wN.svg',
  '/public/pieces/reillycraig/wP.svg',
  '/public/pieces/reillycraig/wQ.svg',
  '/public/pieces/reillycraig/wR.svg',
  // Rhosgfx set
  '/public/pieces/rhosgfx/bB.svg',
  '/public/pieces/rhosgfx/bK.svg',
  '/public/pieces/rhosgfx/bN.svg',
  '/public/pieces/rhosgfx/bP.svg',
  '/public/pieces/rhosgfx/bQ.svg',
  '/public/pieces/rhosgfx/bR.svg',
  '/public/pieces/rhosgfx/wB.svg',
  '/public/pieces/rhosgfx/wK.svg',
  '/public/pieces/rhosgfx/wN.svg',
  '/public/pieces/rhosgfx/wP.svg',
  '/public/pieces/rhosgfx/wQ.svg',
  '/public/pieces/rhosgfx/wR.svg',
  // Riohacha set
  '/public/pieces/riohacha/bB.svg',
  '/public/pieces/riohacha/bK.svg',
  '/public/pieces/riohacha/bN.svg',
  '/public/pieces/riohacha/bP.svg',
  '/public/pieces/riohacha/bQ.svg',
  '/public/pieces/riohacha/bR.svg',
  '/public/pieces/riohacha/wB.svg',
  '/public/pieces/riohacha/wK.svg',
  '/public/pieces/riohacha/wN.svg',
  '/public/pieces/riohacha/wP.svg',
  '/public/pieces/riohacha/wQ.svg',
  '/public/pieces/riohacha/wR.svg',
  // Shapes set
  '/public/pieces/shapes/bB.svg',
  '/public/pieces/shapes/bK.svg',
  '/public/pieces/shapes/bN.svg',
  '/public/pieces/shapes/bP.svg',
  '/public/pieces/shapes/bQ.svg',
  '/public/pieces/shapes/bR.svg',
  '/public/pieces/shapes/wB.svg',
  '/public/pieces/shapes/wK.svg',
  '/public/pieces/shapes/wN.svg',
  '/public/pieces/shapes/wP.svg',
  '/public/pieces/shapes/wQ.svg',
  '/public/pieces/shapes/wR.svg',
  // Spatial set
  '/public/pieces/spatial/bB.svg',
  '/public/pieces/spatial/bK.svg',
  '/public/pieces/spatial/bN.svg',
  '/public/pieces/spatial/bP.svg',
  '/public/pieces/spatial/bQ.svg',
  '/public/pieces/spatial/bR.svg',
  '/public/pieces/spatial/wB.svg',
  '/public/pieces/spatial/wK.svg',
  '/public/pieces/spatial/wN.svg',
  '/public/pieces/spatial/wP.svg',
  '/public/pieces/spatial/wQ.svg',
  '/public/pieces/spatial/wR.svg',
  // Staunty set
  '/public/pieces/staunty/bB.svg',
  '/public/pieces/staunty/bK.svg',
  '/public/pieces/staunty/bN.svg',
  '/public/pieces/staunty/bP.svg',
  '/public/pieces/staunty/bQ.svg',
  '/public/pieces/staunty/bR.svg',
  '/public/pieces/staunty/wB.svg',
  '/public/pieces/staunty/wK.svg',
  '/public/pieces/staunty/wN.svg',
  '/public/pieces/staunty/wP.svg',
  '/public/pieces/staunty/wQ.svg',
  '/public/pieces/staunty/wR.svg',
  // Tatiana set
  '/public/pieces/tatiana/bB.svg',
  '/public/pieces/tatiana/bK.svg',
  '/public/pieces/tatiana/bN.svg',
  '/public/pieces/tatiana/bP.svg',
  '/public/pieces/tatiana/bQ.svg',
  '/public/pieces/tatiana/bR.svg',
  '/public/pieces/tatiana/wB.svg',
  '/public/pieces/tatiana/wK.svg',
  '/public/pieces/tatiana/wN.svg',
  '/public/pieces/tatiana/wP.svg',
  '/public/pieces/tatiana/wQ.svg',
  '/public/pieces/tatiana/wR.svg',
  // Xkcd set
  '/public/pieces/xkcd/bB.svg',
  '/public/pieces/xkcd/bK.svg',
  '/public/pieces/xkcd/bN.svg',
  '/public/pieces/xkcd/bP.svg',
  '/public/pieces/xkcd/bQ.svg',
  '/public/pieces/xkcd/bR.svg',
  '/public/pieces/xkcd/wB.svg',
  '/public/pieces/xkcd/wK.svg',
  '/public/pieces/xkcd/wN.svg',
  '/public/pieces/xkcd/wP.svg',
  '/public/pieces/xkcd/wQ.svg',
  '/public/pieces/xkcd/wR.svg'
];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(PRE_CACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keyList) => {
      return Promise.all(
        keyList.map((key) => {
          if (key !== CACHE_NAME) {
            return caches.delete(key);
          }
        })
      );
    })
  );
});

self.addEventListener('fetch', (e) => {
  e.respondWith(
    caches.match(e.request).then((response) => {
      return response || fetch(e.request);
    })
  );
});
